### ISSUE TITLE
No Keyword To Get Current Location for mobile Web automation

### ISSUE THREAD

**Issue by raghupokuri9035** [jollychang/robotframework-appiumlibrary#101]
Hi Team,

I haven't find most of the keywords for mobile web automation events. How could i avail those keywords like get Title, Get Location, Element Should be visible like in Selenium2Library. I Have started mobile web automation on chrome. Please help me put ASAP.

Thanks in advance.

**Comment by serhatbolsu** [comment]
Hello raghopokuri, thanks for your interest. The issue here is that this library also depends on the capability of appium. Even more specifically Appium Python Client. Please check there first, if those have and this library does not, then we can work on those
