### ISSUE TITLE
click element does not work for webelement object

### ISSUE THREAD

**Issue by qitaos** [jollychang/robotframework-appiumlibrary#105]
this bug from a friend.
He use the keyword "Get WebElements" to get a object list in @{list}.
Then he use "Click Element" @{list}[1] to click the second WebElement object, but it return wrong message about "element has no len()".
 I found this is a bug in function _element_find(), for this line "return elements[0]" .
So I referred to the Selenium2Library to fix this bug.

**Comment by mzbedat** [comment]
Hi,
is it the only change on _element_find() ?
I replaced that method and reinstalled the project, but now it can't locate elements (get elements keyword).

getting:
ValueError: Element locator 'class=pmode8' did not match any elements.

**Comment by mzbedat** [comment]
Hi,
I see your changes in my version but still getting that error!

version::

MacBook:robotframework-appiumlibrary galil$ pip show robotframework-appiumlibrary
---
Metadata-Version: 1.1
Name: robotframework-appiumlibrary
Version: 1.3.5
Summary: app testing library for Robot Framework
Home-page: https://github.com/jollychang/robotframework-appiumlibrary
Author: William Zhang, Xie Lieping, Jari Nurminen, Serhat Bolsu
Author-email: <jollychang@gmail.com>, <frankbp@gmail.com>
License: Apache License 2.0
Location: /Library/Python/2.7/site-packages/robotframework_appiumlibrary-1.3.5-py2.7.egg
Requires: decorator, robotframework, docutils, Appium-Python-Client, selenium, mock, sauceclient, pytest-cov, pytest-xdist, pytest-pythonpath
Classifiers:
  Development Status :: 5 - Production/Stable
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python
  Topic :: Software Development :: Testing

**Comment by konflic** [comment]
True, stil not working on the latest RF.
${catalog} =  Get Webelements  ${CATALOG_ITEMS}
Click Element  ${catalog}[1]

ElementNotInteractableException: Message: element not interactable

**Comment by joshuariveramnltech** [comment]
@konflic It seems your case might be different from theirs, yours says  
 `ElementNotInteractableException: Message: element not interactable`  
```robotframework
${catalog} = Get Webelements ${CATALOG_ITEMS}
Click Element ${catalog}[1]
```
It seems that the element was found but was not interactable during your test run.
