### ISSUE TITLE
Retrieve the contents of a xpath

### ISSUE THREAD

**Issue by CapDam** [jollychang/robotframework-appiumlibrary#107]
Hello,
First of all thank you for the work you do , it helps a lot. But, I have not found a way to recover the contents of a div , a span ... etc . The proposed keywords can retrieve attribute values ​​but I am looking to get the value between the tags.

For example:
<Div id = "test" >
<Span > Text to recover </ span>
</ Div>

Thank you and sorry for my broken English .

**Comment by CapDam** [comment]
sorry I just see that there is already a ticket for the same problem ( Getting Elements Text Attribute #98 ). A solution was made ​​, it would add a new keyword , but how is it done? It publishes a python files containing the keyword and add it ? Because I tried but Robot Framework does not recognize the new keyword .

**Comment by jollychang** [comment]
Can you use `Get Element Attribute `?

**Comment by CapDam** [comment]
Yes I tried but I can not. Let me explain, my XPath is good because I use it to "Click Element" but when I use "Get Element Attribute" with my XPath and "Text" it returns me None so that there is a value. I also used "Value" as an argument.
Can you tell me how to use it in this case?

**Comment by CapDam** [comment]
I did the test and it does not work :
20160416 18:42:55.563 :  INFO : ${context} = WEBVIEW_1
20160416 18:42:56.082 :  INFO : Clicking element '//div[@id="nav-trigger"]'.
20160416 18:42:58.518 :  INFO : Element '//nav/ul/li[1]/a/span' attribute 'value' value 'None' 
20160416 18:42:58.521 :  INFO : ${test1} = ('PASS', None)
20160416 18:42:59.436 :  INFO : Element '//nav/ul/li[1]/a/span' attribute 'text' value 'None' 
20160416 18:42:59.439 :  INFO : ${test2} = ('PASS', None)


And I'm sure the XPath because I tested it with firefox on module and it gives me the right value
