### ISSUE TITLE
Add keyword

### ISSUE THREAD

**Issue by CapDam** [jollychang/robotframework-appiumlibrary#109]
Hi guys,
On windows I modified the _element.py file to add a keyword , Robot Framework acknowledged . I do the same thing on mac OS and it does not work .
So, I was thinking can we add this keyword to avoid having to change each time the file to be locked ?

```
     def get_element_text(self, locator):
		"""
		Get text
		"""
		element = self._element_find(locator, True, True)
		element_text = element.text
		self._info("Element '%s' text: %s " % (locator, element_text))
		return element_text
```

This keyword is much required .

**Comment by jollychang** [comment]
you can open a request
