### ISSUE TITLE
[debug] [Logcat] Starting logcat capture wait too long

### ISSUE THREAD

**Issue by haricarana** [jollychang/robotframework-appiumlibrary#118]
Hi, we started the active using of robotframework-appiumlibrary one week ago. On start everything was fine, but now the "Starting logcat capture" wait too long on Appium server. Somethimes just one minute but mostly hang 5-7 minutes. It's too long time for testing, and I have no idea what can I do. 
As I read, it's also a problem for others. I use AVD of Android Studio. Thanks.

**Comment by serhatbolsu** [comment]
Hello @haricarana thank you for your interest in this library improvements. 
However I believe your issue is about the appium itself. Please try https://discuss.appium.io/ for more help topics and your question. I will close this issue for now, you can always open a new one
