### ISSUE TITLE
Can't select value of picker wheel with appiumlibrary

### ISSUE THREAD

**Issue by Pangp0nd** [jollychang/robotframework-appiumlibrary#119]
## The problem

Hello,
I have issue for select value picker wheel with appiumlibrary with robotframework. I want to select value for picker wheel but I can't set value for picker wheel .

## Environment

* Appium v1.5.3 
* OSX 10.11.5
* Node v6.2.1
* iPhone 6 (9.3)
* emulator/simulator
* appiumlibrary for robotframework.

## Details

**I use appiumlibrary with robotframework.** 

I want to select value from picker wheel but i can't do it .

**cause 1:** May be use worng keyword, i try to use input value (It Pass but value not change), click element ( message : did not match any elements ), tap and scoll  have same message click element.

**cause 2:** May be locator element wrong, i try locator by ios (copy from UIAutomation), class (use UIAPickerWheel).

Do you have other suggestions, please?
Thanks.

**Comment by rz-robsn** [comment]
I have had the same problem before and using the `Input Text` keyword did the trick for me:

    Input Text    class=UIAPickerWheel  MyOption

I am on Appium version 1.5.3 with robotframework-appiumlibrary version 1.3.5.

**Comment by Pangp0nd** [comment]
So good , it works.
thank you very much.
