### ISSUE TITLE
Swipe keyword documentation should be updated

### ISSUE THREAD

**Issue by rz-robsn** [jollychang/robotframework-appiumlibrary#123]
Since appium 1.5, the `end_x` and `end_y` parameters of the `Swipe` keyword on iOS refer to coordinates relative to the `start_x` and `start_y` parameters. Before 1.5, the `end_` parameters used to refer to the relative to the top left corner of the screen.

The `end_x` and `end_y` parameters should be renamed to `offset_x` and `offset_y` and the keyword documentation should be updated accordingly.

See [here](https://github.com/appium/python-client/issues/137) for the counterpart of this issue on the appium python-client repo.

**Comment by serhatbolsu** [comment]
You are correct @rz-robsn this has changed with 1.5.x . We also had problem figuring this out. 
Please send a pull request if you have time: also make sure to mention an example with numeric entry, such as : ${350} since robotframework default is always string

**Comment by serhatbolsu** [comment]
Fixed with #125
