### ISSUE TITLE
Swipe keyword parameters not completely renamed

### ISSUE THREAD

**Issue by MarkkuTurunen** [jollychang/robotframework-appiumlibrary#126]
Parameters offset_x and offset_y are not used. driver.swipe() receives parameters by their old names end_x and end_y.

**Comment by serhatbolsu** [comment]
please check my comment on #125

**Comment by smaspe** [comment]
I have read your comment and checked the code, I don't understand why this issue is closed. Trying to use `Swipe` results in a crash saying `'end_x' is not defined`, obviously.

**Comment by serhatbolsu** [comment]
@smaspe you can get the master code right now, issue is fixed on master

**Comment by smaspe** [comment]
@serhatbolsu thanks, but no thanks. Last time I updated, albeit to a released version, I got this regression packaged with it. So I will not get the current code from master. Not to mention it would require a significant change in the way the rest of the team uses the test suites (we are using `pip` to install all the dependencies, switching to getting the code is far from ideal). I'll just apply the fix locally, add a patch in the install procedure, and wait for the next release. And test it, too, before making the update.

**Comment by smaspe** [comment]
Also, I don't understand why this issue is closed (given that it is present on the latest release.)

**Comment by MarkkuTurunen** [comment]
@serhatbolsu It is good that this has been fixed in the master and thus it will be available in the next release.  Also in our case we stick to published releases and we do not fetch a snapshot from master.

**Comment by smaspe** [comment]
@serhatbolsu thanks for the release!

@MarkkuTurunen if you have not seen, there just was a new release addressing specifically that issue.
