### ISSUE TITLE
keyword for Appium precise tap?

### ISSUE THREAD

**Issue by bcohen44** [jollychang/robotframework-appiumlibrary#33]
I don't see a keyword for a precise tab.  I have an embedded URL on a UIAWindow that has no element to use the existing "Tap" keyword.  I need to tap with precise coordinates.
Here it is in the Inspector:

![appium_inspector](https://cloud.githubusercontent.com/assets/6190190/5670533/a45c51d2-974e-11e4-9943-f29845a518da.png)

**Comment by jollychang** [comment]
I Can't find it in appium documentation

You can open a discuss in appium maillist.

William
--------------------
This is the life!
