### ISSUE TITLE
getting AppiumLibrary' failed: ImportError: No module named sauceclient after new install

### ISSUE THREAD

**Issue by bcohen44** [jollychang/robotframework-appiumlibrary#36]
simple sudo pip install robotframework-appiumlibrary installation.  When I try to run my test(s) I get this:

```
[ ERROR ] Error in file '/Users/si-briancohen/jenkins_home/workspace/Sys_Integrity_Automation/consumer_mobile/resources/resources_mobile.robot': Importing test library 'AppiumLibrary' failed: ImportError: No module named sauceclient
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/AppiumLibrary/__init__.py", line 4, in <module>
    from keywords import *
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/AppiumLibrary/keywords/__init__.py", line 5, in <module>
    from _element import _ElementKeywords
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/AppiumLibrary/keywords/_element.py", line 3, in <module>
    from appium.webdriver.common.touch_action import TouchAction
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/__init__.py", line 18, in <module>
    from .saucetestcase import SauceTestCase
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appium/saucetestcase.py", line 20, in <module>
    from sauceclient import SauceClient
PYTHONPATH:
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robot/libraries
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
  /usr/local/bin
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.9.7-py2.7.egg
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.4-py2.7.egg
  /usr/local/lib/python2.7/site-packages/setuptools-0.9.7-py2.7.egg
  /usr/local/lib/python2.7/site-packages/pip-1.4-py2.7.egg
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /Library/Python/2.7/site-packages
  /usr/local/lib/python2.7/site-packages
```

**Comment by jollychang** [comment]
try
`pip install --upgrade robotframework-appiumlibrary`

**Comment by bcohen44** [comment]
Same thing.  Upgrade didn't do it, since I'm on the latest.  Any other suggestions?

```
bos-mac-si:Sys_Integrity_Automation si-briancohen$ sudo pip install --upgrade robotframework-appiumlibrary
Password:
Requirement already up-to-date: robotframework-appiumlibrary in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: decorator>=3.3.2 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: robotframework>=2.6.0 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: docutils>=0.8.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: Appium-Python-Client>=0.5 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: mock>=1.0.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-cov>=1.8.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-xdist>=1.11 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-pythonpath>=0.4 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: selenium>=2.41.0 in /usr/local/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already up-to-date: py>=1.4.22 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: pytest>=2.6.0 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: coverage>=3.7.1,<4.0a1 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: cov-core>=1.14.0 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: execnet>=1.1 in /usr/local/lib/python2.7/site-packages (from pytest-xdist>=1.11->robotframework-appiumlibrary)
Cleaning up...
```

**Comment by jollychang** [comment]
as your log，it installed successful

**Comment by bcohen44** [comment]
But I'm still getting that Erie about sauceclient

On Tuesday, January 20, 2015, William Zhang <notifications@github.com>
wrote:

> as your log，it installed successful
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jollychang/robotframework-appiumlibrary/issues/36#issuecomment-70755319>
> .
>


-- 
-Brian

**Comment by jollychang** [comment]
could you paste me the whole log?

**Comment by bcohen44** [comment]
I tried uninstalling and installing, a few times...same thing. Here is the log:

```
bos-mac-si:Sys_Integrity_Automation si-briancohen$ sudo pip uninstall robotframework-appiumlibrary
Password:
Uninstalling robotframework-appiumlibrary:
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_applicationmanagement.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_applicationmanagement.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_element.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_element.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_keyevent.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_keyevent.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_logging.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_logging.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_runonfailure.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_runonfailure.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_screenshot.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_screenshot.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_touch.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_touch.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_waiting.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_waiting.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/keywordgroup.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/keywordgroup.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/elementfinder.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/elementfinder.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/applicationcache.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/applicationcache.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/version.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/version.pyc
  /usr/local/lib/python2.7/site-packages/ez_setup.py
  /usr/local/lib/python2.7/site-packages/ez_setup.pyc
  /usr/local/lib/python2.7/site-packages/robotframework_appiumlibrary-1.2.3-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled robotframework-appiumlibrary
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ sudo pip install --upgrade robotframework-appiumlibrary
Downloading/unpacking robotframework-appiumlibrary
  Downloading robotframework-appiumlibrary-1.2.3.tar.gz
  Running setup.py egg_info for package robotframework-appiumlibrary
    
Requirement already up-to-date: decorator>=3.3.2 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: robotframework>=2.6.0 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: docutils>=0.8.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: Appium-Python-Client>=0.5 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: mock>=1.0.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-cov>=1.8.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-xdist>=1.11 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: pytest-pythonpath>=0.4 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already up-to-date: selenium>=2.41.0 in /usr/local/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already up-to-date: py>=1.4.22 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: pytest>=2.6.0 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: coverage>=3.7.1,<4.0a1 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: cov-core>=1.14.0 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already up-to-date: execnet>=1.1 in /usr/local/lib/python2.7/site-packages (from pytest-xdist>=1.11->robotframework-appiumlibrary)
Installing collected packages: robotframework-appiumlibrary
  Running setup.py install for robotframework-appiumlibrary
    
Successfully installed robotframework-appiumlibrary
Cleaning up...
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ sudo pip uninstall robotframework-appiumlibrary
Uninstalling robotframework-appiumlibrary:
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_applicationmanagement.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_applicationmanagement.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_element.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_element.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_keyevent.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_keyevent.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_logging.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_logging.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_runonfailure.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_runonfailure.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_screenshot.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_screenshot.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_touch.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_touch.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_waiting.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/_waiting.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/keywordgroup.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/keywords/keywordgroup.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/elementfinder.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/locators/elementfinder.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/__init__.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/__init__.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/applicationcache.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/utils/applicationcache.pyc
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/version.py
  /usr/local/lib/python2.7/site-packages/AppiumLibrary/version.pyc
  /usr/local/lib/python2.7/site-packages/ez_setup.py
  /usr/local/lib/python2.7/site-packages/ez_setup.pyc
  /usr/local/lib/python2.7/site-packages/robotframework_appiumlibrary-1.2.3-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled robotframework-appiumlibrary
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ 
bos-mac-si:Sys_Integrity_Automation si-briancohen$ sudo pip install robotframework-appiumlibrary
Downloading/unpacking robotframework-appiumlibrary
  Downloading robotframework-appiumlibrary-1.2.3.tar.gz
  Running setup.py egg_info for package robotframework-appiumlibrary
    
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.3.2 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): robotframework>=2.6.0 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.8.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): Appium-Python-Client>=0.5 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): mock>=1.0.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): pytest-cov>=1.8.1 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): pytest-xdist>=1.11 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): pytest-pythonpath>=0.4 in /usr/local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): selenium>=2.41.0 in /usr/local/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/site-packages (from Appium-Python-Client>=0.5->robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.22 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2.6.0 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.7.1,<4.0a1 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): cov-core>=1.14.0 in /usr/local/lib/python2.7/site-packages (from pytest-cov>=1.8.1->robotframework-appiumlibrary)
Requirement already satisfied (use --upgrade to upgrade): execnet>=1.1 in /usr/local/lib/python2.7/site-packages (from pytest-xdist>=1.11->robotframework-appiumlibrary)
Installing collected packages: robotframework-appiumlibrary
  Running setup.py install for robotframework-appiumlibrary
    
Successfully installed robotframework-appiumlibrary
Cleaning up...
```

**Comment by jollychang** [comment]
@bcohen44 as your log mentioned. 
`Successfully installed robotframework-appiumlibrary`

**Comment by bcohen44** [comment]
@jollychang, I get that it installed successfully.  Please address the specific error thrown when I try to run my Robot test about the sauceclient, what it is that?  Regardless if it installed "correctly", I cannot run a pybot command line test with this sauceclient error.

**Comment by jollychang** [comment]
@bcohen44 got that fix in https://github.com/jollychang/robotframework-appiumlibrary/commit/92ca8662f3ffefca052562562ece2559827f51fa

try again? 

`pip install --upgrade robotframework-appiumlibrary`

**Comment by bcohen44** [comment]
@jollychang, 1.24 fix worked...thanks a bunch!

**Comment by seeamkhan** [comment]
Hi @jollychang 
I am facing the import error for 'robotframework-appiumlibrary-1.4.5.4'
I tried uninstall and then again install also tried to upgrade it but could not resolve the issue.
Here is my log for library installation:
`pip install robotframework-appiumlibrary --user
Collecting robotframework-appiumlibrary
Requirement already satisfied: docutils>=0.8.1 in /home/abqu/.local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied: robotframework>=2.6.0 in /home/abqu/.local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied: selenium>=2.47.1 in /home/abqu/.local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied: kitchen>=1.2.4 in /home/abqu/.local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied: decorator>=3.3.2 in /home/abqu/.local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Requirement already satisfied: Appium-Python-Client>=0.20 in /home/abqu/.local/lib/python2.7/site-packages (from robotframework-appiumlibrary)
Installing collected packages: robotframework-appiumlibrary
Successfully installed robotframework-appiumlibrary-1.4.5.4`

And here is the error's after running the demo robot file:
`pybot demo.txt 
[ ERROR ] Error in file '/home/abqu/Documents/appium-rnd/demo.txt': Importing test library 'AppiumLibrary' failed: ImportError: No module named six
Traceback (most recent call last):
  File "/home/abqu/.local/lib/python2.7/site-packages/AppiumLibrary/__init__.py", line 4, in <module>
    from AppiumLibrary.keywords import *
  File "/home/abqu/.local/lib/python2.7/site-packages/AppiumLibrary/keywords/__init__.py", line 5, in <module>
    from ._element import _ElementKeywords
  File "/home/abqu/.local/lib/python2.7/site-packages/AppiumLibrary/keywords/_element.py", line 3, in <module>
    from AppiumLibrary.locators import ElementFinder
  File "/home/abqu/.local/lib/python2.7/site-packages/AppiumLibrary/locators/__init__.py", line 3, in <module>
    from .elementfinder import ElementFinder
  File "/home/abqu/.local/lib/python2.7/site-packages/AppiumLibrary/locators/elementfinder.py", line 3, in <module>
    from AppiumLibrary import utils
  File "/home/abqu/.local/lib/python2.7/site-packages/AppiumLibrary/utils/__init__.py", line 1, in <module>
    import six
PYTHONPATH:
  /home/abqu/.local/bin
  /usr/lib/python2.7
  /usr/lib/python2.7/plat-x86_64-linux-gnu
  /usr/lib/python2.7/lib-tk
  /usr/lib/python2.7/lib-old
  /usr/lib/python2.7/lib-dynload
  /home/abqu/.local/lib/python2.7/site-packages
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages/gtk-2.0
==============================================================================
Demo :: demo for appium library                                               
==============================================================================
test_demo                                                             'Why importing appiumlibrary showing error??'
test_demo                                                             | FAIL |
No keyword with name 'Open Application' found.
------------------------------------------------------------------------------
Demo :: demo for appium library                                       | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/abqu/Documents/appium-rnd/output.xml
Log:     /home/abqu/Documents/appium-rnd/log.html
Report:  /home/abqu/Documents/appium-rnd/report.html`

Can you please suggest me, how can I resolve this issue?

The demo.txt file I tried to run is as below:
`Library	 AppiumLibrary  5

Documentation   demo for appium library

Force Tags      demo

*** Test Cases ***

test_demo

    [Tags]  regression
    log to console  'Why importing appiumlibrary showing error??'

    Open Application  http://10.136.16.34:4723/wd/hub/status  platformName=Android  platformVersion=7.1.1  deviceName=Nexus-5X-API-25  app=com.android.browser  automationName=appium  appPackage=com.android.browser  appActivity=AddBookmarkPage`

**Comment by seeamkhan** [comment]
Hi, sorry for bothering with irrelevant question. I have found the issue was due to the missing python module 'six'. I have installed it and now the error gone.
Thanks anyway. :)

**Comment by vnvbsudhakar** [comment]
@seeamkhan: Hey, can you please tell me how you installed only that module alone.

**Comment by seeamkhan** [comment]
@vnvbsudhakar: I think pip install six worked for me.

**Comment by vnvbsudhakar** [comment]
@seeamkhan : yeah thanks, it worked for me.
By any chance are you working on Appium now...

**Comment by Nivedita-Mirjikar** [comment]
@seeamkhan Even after installing six its not working for me? Any other solution.
Thanks in advance

**Comment by Nivedita-Mirjikar** [comment]
@seeamkhan Its solved now after installing I had to restart the ride. Thank you

**Comment by Sureshbtvr** [comment]
Hello All,

I am facing same issue. Unable to launch App. got following error "No keyword with name 'Open Application' found."

Here i'm attaching log file and sample code.I am using Pycharm IDE.
I tried all possible steps mentioned in above comments. 

[testlogs.txt](https://github.com/serhatbolsu/robotframework-appiumlibrary/files/2804155/testlogs.txt)


Thanks in advance

**Comment by Srihari88** [comment]
@Sureshbtvr Could you please Appium logs here.

**Comment by miewliie** [comment]
Hello, 
I'm facing the same issue too. I'm not sure what I am missing.
Any suggestion, please.
Thank you,

**here from my logs.**
[ ERROR ] Error in file '/Users/miew/Documents/Android/Resources/demo.robot': Importing test library 'App
iumLibrary' failed: ImportError: No module named AppiumLibrary
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /Library/Python/2.7/site-packages/pip-18.1-py2.7.egg
  /usr/bin

  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /Library/Python/2.7/site-packages
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC

**Comment by fatenBAB** [comment]
Hi everyone,
I'm facing the same issue now and it's really blocking me right now,
everything was okay but suddenly I have the error msg 

Importing test library 'AppiumLibrary' failed: ImportError: No module named AppiumLibrary
error	02-Dec-2020 12:58:40	Traceback (most recent call last):
error	02-Dec-2020 12:58:40	  None
error	02-Dec-2020 12:58:40	PYTHONPATH:
error	02-Dec-2020 12:58:40	  /usr/local/bin
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
error	02-Dec-2020 12:58:40	  /Users/itmaster/Library/Python/2.7/lib/python/site-packages
error	02-Dec-2020 12:58:40	  /Library/Python/2.7/site-packages
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
error	02-Dec-2020 12:58:40	  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC

**Comment by tank0232** [comment]
I still face the same issue

[ ERROR ] Error in file '/Users/kah.heng.ryan.tan/SPA/Robot-files/1-Onboarding/1_Onboard.robot' on line 5: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/kah.heng.ryan.tan/Library/Python/3.8/bin
  /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python38.zip
  /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8
  /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/lib-dynload
  /Users/kah.heng.ryan.tan/Library/Python/3.8/lib/python/site-packages
  /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages
  
  any solution for this??

**Comment by Cristiano-Lobo** [comment]
My problem was solved with the following commands:
- pip install six or python -m pip install six
- pip install selenium
- python -m pip install -U selenium

**Comment by watanak** [comment]
Hello All, currently I got error  
"Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'"

I am using:
- python version: 3.9.6
- appium 2.0.1
- robotframework: 7.0.0
- robotframeworka-appiumlibrary: 2.0.0

Please help me a bit. Thank

**Comment by Suphakorn95** [comment]
Hello All, I'm facing same error 
"Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action' "

I am using: 

- python version: 3.12.0
- appium 2.5.1
- robotframework: 7.0.0
- robotframeworka-appiumlibrary: 2.0.0

Please help me. Thanks you in advance.

**Comment by AlexsanderWill** [comment]
Hello , I'm facing same error
"Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'"

I am using:

python version: 3.10.12
appium 2.5.3
robotframework: 7.0.0
robotframeworka-appiumlibrary: 2.0.0

Please help me a bit. Thank

**Comment by watanak** [comment]
> Hello , I'm facing same error "Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'"
> 
> I am using:
> 
> python version: 3.10.12 appium 2.5.3 robotframework: 7.0.0 robotframeworka-appiumlibrary: 2.0.0
> 
> Please help me a bit. Thank

downgrade Python Appium-Client to Appium-Python-Client==3.2.1
