### ISSUE TITLE
Error: pybot OrangeDemoApp.html

### ISSUE THREAD

**Issue by yanshuai** [jollychang/robotframework-appiumlibrary#37]
I have installed robotframework-appiumlibrary through pip command, but when I entered demo and executed ```pybot OrangeDemoApp.html```, it has the following errors:
```
Importing test library 'AppiumAndroidLibrary' failed: ImportError: No module named AppiumAndroidLibrary
```

How can I fix it?

**Comment by jollychang** [comment]
Sorry， delete html demo，you can try txt demo
https://github.com/jollychang/robotframework-appiumlibrary/commit/69e105aadaed3003aa2dc9a0db2434319499ae7a
