### ISSUE TITLE
Please add implicitly_wait

### ISSUE THREAD

**Issue by BenjaminZaiser** [jollychang/robotframework-appiumlibrary#39]
Hi jollychang,

I'm currently writing my first test case for an Android app by using your Appium library.
Unfortunately I'm experiencing some problems with the Page Should Contain Element keyword. It will only pass, if I add a Sleep  1s keyword before the assertion, because only then the app has finished with drawing the screen and only then the desired element is available.

To circumvent the additional Sleep keyword, I guess the Appium Python library provides the implicitly_wait functionality. Please could you add that feature to your library so it can be used within the Robotframework?

Thanks
Ben

**Comment by jollychang** [comment]
I am busy with some tasks, Could you open a pull request for this?

**Comment by BenjaminZaiser** [comment]
Maybe you can just add the following code to _applicationmanagement.py
```
    def set_implicitly_wait(self, timeout):
        """Sets the Implicit Wait Timeout to the given value"""
        self._current_application().implicitly_wait(timeout)
```
Thanks
Ben

**Comment by jollychang** [comment]
Could you open a pull request with testcase? thanks

**Comment by vvvvaib** [comment]
I see that implicit wait keyword is not yet implemented. Any reason why this was closed?
