### ISSUE TITLE
My test start in web view context,and then switch to the native app context.when switching from native app context back to web view context,the test goes wrong.

### ISSUE THREAD

**Issue by killallkill** [jollychang/robotframework-appiumlibrary#40]
here the test code:
public void Test03_pan() throws InterruptedException{
		
		String origContext = driver.getContext();
		System.out.println(origContext);
		
		WebElement btnPan = driver.findElementById("btn-pan");
		btnPan.click();
		Thread.sleep(3000);
		
		
		System.out.println("start switch");
		driver.context("NATIVE_APP");
		String newContext = driver.getContext();
		System.out.println(newContext);
		

		driver.tap(1, 100, 400, 1000);
		driver.swipe(100, 400, 100, 500, 5000);
		
		System.out.println("switch back");
		driver.switchTo().window("WEBVIEW_1");
		String s = driver.getContext();
		System.out.println(s);

	}
I have tried so much,but none worked.
Can I get your suggestions?
best regards.

**Comment by jollychang** [comment]
It is not a issue  for robotframework-appiumlibrary
