### ISSUE TITLE
shake is throwing, 'message not implemented yet' on android

### ISSUE THREAD

**Issue by faran** [jollychang/robotframework-appiumlibrary#41]
working with Android i am getting below error when trying to use keyword "Shake"

> info: [debug] Responding to client that a method is not implemented
> info: <-- POST /wd/hub/session/c2ff7fb7-7837-4830-95fd-c3fcf5a1a529/appium/device/shake 501 3.294 ms - 158 

Can you please check, many thanks in advance.

**Comment by jollychang** [comment]
Could you provide more detail? code and logging

**Comment by faran** [comment]
this is my script

![image](https://cloud.githubusercontent.com/assets/2789412/6483267/f366e484-c266-11e4-98cd-91f1deb84778.png)


I don't have much logging coming out of Appium, i copied the most useful bit i can see in description already. If there is a way to capture more detailed logging can you please share with me. Many thanks.

**Comment by jollychang** [comment]
what's your appium server version?  Could you try latest version of appium server?

**Comment by faran** [comment]
i am using 1.3.4.1 on windows, connecting to samsung galaxy s5 with jb

**Comment by jollychang** [comment]
This is appium's issue , you can check in appium project

**Comment by Digi-yatin** [comment]
@faran Did you find a solution to this issue? Could you share the link/solution here.

Thanks in advance.
