### ISSUE TITLE
"Page should contain element" fails if locator strategy (id/name/etc.) is missing

### ISSUE THREAD

**Issue by yahman72** [jollychang/robotframework-appiumlibrary#42]
`Page should contain element` fails always with an ` AttributeError: 'module' object has no attribute 'escape_xpath_value'` error

<pre>
20150305 19:46:57.047 - INFO - +----- START KW: AppiumLibrary.Page Should Contain Element [ com.android.contacts:id/digits ]
20150305 19:46:57.725 - FAIL - AttributeError: 'module' object has no attribute 'escape_xpath_value'
20150305 19:46:57.725 - DEBUG - Traceback (most recent call last):
  File "<string>", line 2, in page_should_contain_element
  File "C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.2.4-py2.7.egg\AppiumLibrary\keywords\keywordgroup.py", line 14, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.2.4-py2.7.egg\AppiumLibrary\keywords\_element.py", line 112, in page_should_contain_element
    if not self._is_element_present(locator):
  File "C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.2.4-py2.7.egg\AppiumLibrary\keywords\_element.py", line 272, in _is_element_present
    elements = self._element_finder.find(application, locator, None)
  File "C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.2.4-py2.7.egg\AppiumLibrary\locators\elementfinder.py", line 28, in find
    return strategy(browser, criteria, tag, constraints)
  File "C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.2.4-py2.7.egg\AppiumLibrary\locators\elementfinder.py", line 94, in _find_by_default
    return self._find_by_key_attrs(browser, criteria, tag, constraints)
  File "C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.2.4-py2.7.egg\AppiumLibrary\locators\elementfinder.py", line 101, in _find_by_key_attrs
    xpath_criteria = utils.escape_xpath_value(criteria)
20150305 19:46:57.725 - INFO - +----- END KW: AppiumLibrary.Page Should Contain Element (678)
</pre>

**Comment by yahman72** [comment]
oops - this works fine if you remember to pass the locator strategy to the keyword.
This fails if you use `com.android.contacts:id/digits` instead of `identifier = com.android.contacts:id/digits`

**Comment by jollychang** [comment]
yes, it need prefix; as Document See [introduction](http://jollychang.github.io/robotframework-appiumlibrary/doc/AppimuLibrary.html#Introduction) for details about locating elements.
https://github.com/jollychang/robotframework-appiumlibrary/blob/master/src/AppiumLibrary/locators/elementfinder.py#L25

**Comment by yahman72** [comment]
This is now a bit cosmetic but the error handling could be more user-friendly e.g throw an understandable `locator strategy missing` error instead of that very cryptic `AttributeError: 'module' object has no attribute 'escape_xpath_value'`.

**Comment by eshah17** [comment]
For "Wait Until Page Contains Element" Keyword: when I use 'id' as prefix it error out with error: WebDriverException: Message: Invalid locator strategy: css selector  and if I don't use 'id' as prefix  then it error out with error : AttributeError: 'module' object has no attribute 'escape_xpath_value'.

**Comment by jollychang** [comment]
If it is not prefix, it will pass to _find_by_default. 
should I handle all without prefix,
any suggestion ?
```
    def _find_by_default(self, browser, criteria, tag, constraints):
        if criteria.startswith('//'):
            return self._find_by_xpath(browser, criteria, tag, constraints)
        return self._find_by_key_attrs(browser, criteria, tag, constraints)
```

**Comment by eshah17** [comment]
in robot framework - selenium , by default it finds element by id or name if no prefix is added.

**Comment by jollychang** [comment]
@eshah17 robotframework-selenium2library is find element default by css, I think add prefix is better for stability and exactly find element.

**Comment by yahman72** [comment]
Yeah, I think prefix is better for clarity - and as I already mentioned earlier, throw an "human-readable" error if the pre-fix is missing or is unknown
