### ISSUE TITLE
text input: append and replace

### ISSUE THREAD

**Issue by yahman72** [jollychang/robotframework-appiumlibrary#44]
An enhancement idea: I think it would be good to have possibility to replace a text in a text field with one keyword.
I.e. instead of
<pre>
Clear Text   identifier = com.me.myApp:id/textField
Input Text   identifier = com.me.myApp:id/textField    ExampleText
</pre>
do just
1) `Input Text        identifier = com.me.myApp:id/textField    ExampleText     replace=True`
*or*
2) `Replace Text     identifier = com.me.myApp:id/textField    ExampleText`

What do you think? Should I create a PR for this?
If yes, which option? I'd prefer 1)

One Keyword would make the execution faster and there already different methods for this on Appium side: `send_keys()` when appending and `set_text()` when replacing.

**Comment by jollychang** [comment]
I think user can't create with the two  keywords by themselves 

```
Replace Text    
    [Arguments]    ${identifier}   ${text}  
    Clear Text   identifier = ${identifier}
    Input Text   identifier = ${identifier}    ${text}  
```
