### ISSUE TITLE
Install APK on real device with appium in RF

### ISSUE THREAD

**Issue by SiddheshS** [jollychang/robotframework-appiumlibrary#46]
There is no such a keyword in appium library of RF(Robot Framework) to install or Uninstall apk on the real devices. Do we have any method in appium to do the same? any example?

With the help of Android library its easy but i am looking solution for appium.

Any help will be appreciated... :-)

**Comment by jollychang** [comment]
you can try `Process` for `adb install`
http://robotframework.org/robotframework/latest/libraries/Process.html

**Comment by SiddheshS** [comment]
Thanks for reply.

I tried it i mean adb install XX.apk, But i have no idea how to use it in
robot framework. Could you please give me an example so that i can move
ahead?

Siddhesh

**Comment by jollychang** [comment]
```

Run Process	adb install demo.apk
```

**Comment by SiddheshS** [comment]
Really thanks,

It worked for me, it was so easy...[?]

**Comment by SiddheshS** [comment]
Hi again,

Do we have something in place for iOS? I am planning to install or
uninstall ios app with the help of appium in robot framework. I dont want
to go for calabash, i am searching an alternative....
