### ISSUE TITLE
Getting Elements Text Attribute

### ISSUE THREAD

**Issue by ponkar** [jollychang/robotframework-appiumlibrary#47]
User activity - 
I am trying to fetch the text of the Button or Label, and copy it to clipboard or temporary variable in my test script. This I cannot achieve using RF capability but can achieve through pythons appium client library.

**Comment by jollychang** [comment]
Could you provide more log and detail command？

**Comment by ponkar** [comment]
I found it has been implemented and the keyword is Get Text

**Comment by valaxy** [comment]
@ponkar are you sure? I really didn't find the keyword of **Get Text**, please check http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html

**Comment by gnmagno** [comment]
I am also having the same problem, is there a way for me to get staticText value in iOS?

**Comment by pandabat** [comment]
I didn't either - the reason for closing is invalid (or lacks a coherent explanation of what is meant). Reopening this in new bug/issue  Getting Elements Text Attribute #98

**Comment by pandabat** [comment]
You can edit your _elements.py and add something like:

    def get_element_text(self, locator):
        element = self._element_find(locator, True, True)
        element_text = element.text
        self._info("Element '%s' text: %s " % (locator, element_text))
        return element_text

Should work until they add something official
