### ISSUE TITLE
Importing test library '/path/AppiumLibrary' failed: ValueError: Expecting , delimiter: line 171 column 5 (char 4660)

### ISSUE THREAD

**Issue by rockyav** [jollychang/robotframework-appiumlibrary#48]
I got stuck when running testing here:

[ ERROR ] Error in file '/Users/vunguyen/automation/customclient/libs/keywordsLib/customAppKeywords.txt': Importing test library '/Users/vunguyen/automation/customclient/tools/AppiumLibrary' failed: ValueError: Expecting , delimiter: line 171 column 5 (char 4660)
Traceback (most recent call last):
  File "/Users/vunguyen/automation/customclient/tools/AppiumLibrary/__init__.py", line 4, in <module>
    from keywords import *
  File "/Users/vunguyen/automation/customclient/tools/AppiumLibrary/keywords/__init__.py", line 11, in <module>
    from _account import _AccountKeywords
  File "/Users/vunguyen/automation/customclient/tools/AppiumLibrary/keywords/_account.py", line 14, in <module>
    from base import base
  File "/Users/vunguyen/automation/customclient/libs/pyLib/base.py", line 15, in <module>
    from GlobalVariables import *
  File "/Users/vunguyen/automation/customclient/libs/pyLib/GlobalVariables.py", line 88, in <module>
    device_platform,device_port =get_json_file()
  File "/Users/vunguyen/automation/customclient/libs/pyLib/GlobalVariables.py", line 79, in get_json_file
    dev_info = json.load(json_file)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
PYTHONPATH:
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robot/libraries
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
  /Library/Frameworks/Python.framework/Versions/2.7/bin
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.2.5-py2.7.egg
  /Users/vunguyen/automation/customclient/tools/AppiumLibrary
  /Users/vunguyen/automation/customclient/tools/AppiumLibrary/keywords
  /Users/vunguyen/automation/customclient/tools/AppiumLibrary/locators
  /Users/vunguyen/automation/customclient/tools/AppiumLibrary/utils
  /Users/vunguyen/automation/customclient/libs/keywordsLib
  /Users/vunguyen/automation/customclient/libs/pyLib
  /Users/vunguyen/automation/customclient/libs/testSuites
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /Library/Python/2.7/site-packages

**Comment by jollychang** [comment]
could you provide more logs?
such as content of `/Users/vunguyen/automation/customclient/libs/keywordsLib/customAppKeywords.txt`

**Comment by rockyav** [comment]
The file “customAppKeywords.txt” is the file content the keyword for iOS testing. I don’t have permission to give other. 
I only provide a part :

*** Settings ***
Documentation       BASE LIBRARY: This is library which contains most commonly used keywords across all testsuites and testcases and also imports all necessary modules, keywords, variables, and python libraries
Library             Collections
Library             String
Library             ${APPIUM_ROBOT_LIB}
#Library            ${APPIUM_IOS_LIB}       #SHOULD ADD OR NOT?
Library             ${RESOURCE_HOME}/pyLib/base.py              ${DEVICE_NAME}
Library             ${RESOURCE_HOME}/pyLib/deviceAction.py      ${DEVICE_NAME}
#Library            ${RESOURCE_HOME}/pyLib/accountAction.py     ${DEVICE_NAME}
#Library            ${RESOURCE_HOME}/pyLib/device.py            ${DEVICE_NAME}
Resource            myPlans.txt
Resource            billing.txt
Resource            manageDevices.txt
Resource            specialOffers.txt
Resource			oobe.txt
Resource            private.txt
Resource            ${TENANT_NAME}.txt
Variables           GlobalVariables.py

*** Variables ***
${automation_name}      
${local_sleep_time}         30
${local_timeout}            30
${total_sleep_time}         ${sleep_time} + ${local_sleep_time}
${total_timeout}            ${timeout} + ${local_timeout}
${this_error_msg}           None
${this_oncode}              None
${default_partner_env}      ${zact_qaautomation}
# tracking login to skip next time
${login_counter}            0
${tenant_name}              ZACT
${android_app_package}		com.itsoninc.android.itsonclient
${this_email_address}		None
 
*** Keywords ***
Open Application On Device
    [Documentation]         Retrieve all necessary information about the device and launch an appium session.
    ...                     Note: Make sure your device is stated within deviceManifest.
    Log To Console          Starting application
    listOfDevices
    ${port}=                get_port
    ${platform_name}=       get_platform
    ${platform_version}=    get_version
    ${app}=                 get_app
    ${device_type_tmp}      get_device_info
    Set Suite Variable      ${device_type}      ${device_type_tmp}
	${current_device_email}	get_emailid
    ${this_email_address}=	Set Variable If		'${this_email_address}' == 'None'           ${current_device_email}        ${this_email_address}	
    ${android_app_package}=	Set Variable If				'${app}' == 'None'      	  ${android_app_package}	     
    ...						'${app}' == '${EMPTY}'		${android_app_package}	      ${app}    
    Run Keyword If          '${platform_name}' == 'Android'     Run Keyword And Ignore Error     open_application    ${remote_url}   ${platform_name}    ${platform_version}     ${device_name}      ${app}  ${automation_name}  ${android_app_package}      ${android_app_activity}
    Run Keyword If          '${platform_name}' == 'iOS'         Run Keyword And Ignore Error     open_application    ${remote_url}   ${platform_name}    ${platform_version}     ${device_name}      ${app}
	Log To Console			${android_app_package}
    Sleep                   ${timeout}               
    : FOR    ${i}      IN RANGE    2
    \		Log To Console          Detecting any un-expected windows/errors popup during Open Application. Retrying... ${i+1}/2
	\		${status}               ${verify_text}=     			Run Keyword And Ignore Error    Wait Until Page Contains    		$




————
And here is the bach_profile:


# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
# PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
PATH="/Library/Python/2.7:${PATH}"
export PATHJAVA_HOME=/usr/bin/java
export JAVA_HOME
PYTHON_PATH=/usr/bin
export PYTHON_PATH
export DYLD_LIBRARY_PATH=/Users/vunguyen/imobiledevice-macosx/:$DYLD_LIBRARY_PA$
PATH=${PATH}:/Users/vunguyen/imobiledevice-macosx/


# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
PATH="/Library/Python/2.7:${PATH}"
export PATH

ROOT_HOME=$(pwd)

export ANDROID_HOME=$ROOT_HOME/automation/android-sdk-linux
#export PYTHON_PATH="/Library/Python/2.7"
#export PYTHON_PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin"
export JAVA_HOME="Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk"
export PATH=${PATH}:$JAVA_HOME:$PYTHON_PATH
export PATH=$PATH:$HOME/.npm-packages/bin

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

All the patch are correct ?

Thanks so much,
VuNguyen

**Comment by rockyav** [comment]
Hi,

The file “customAppKeywords.txt” is the file content the keyword for iOS testing. I don’t have permission to give other. 
I only provide a part :

*** Settings ***
Documentation       BASE LIBRARY: This is library which contains most commonly used keywords across all testsuites and testcases and also imports all necessary modules, keywords, variables, and python libraries
Library             Collections
Library             String
Library             ${APPIUM_ROBOT_LIB}
#Library            ${APPIUM_IOS_LIB}       #SHOULD ADD OR NOT?
Library             ${RESOURCE_HOME}/pyLib/base.py              ${DEVICE_NAME}
Library             ${RESOURCE_HOME}/pyLib/deviceAction.py      ${DEVICE_NAME}
#Library            ${RESOURCE_HOME}/pyLib/accountAction.py     ${DEVICE_NAME}
#Library            ${RESOURCE_HOME}/pyLib/device.py            ${DEVICE_NAME}
Resource            myPlans.txt
Resource            billing.txt
Resource            manageDevices.txt
Resource            specialOffers.txt
Resource			oobe.txt
Resource            private.txt
Resource            ${TENANT_NAME}.txt
Variables           GlobalVariables.py

*** Variables ***
${automation_name}      
${local_sleep_time}         30
${local_timeout}            30
${total_sleep_time}         ${sleep_time} + ${local_sleep_time}
${total_timeout}            ${timeout} + ${local_timeout}
${this_error_msg}           None
${this_oncode}              None
${default_partner_env}      ${zact_qaautomation}
# tracking login to skip next time
${login_counter}            0
${tenant_name}              ZACT
${android_app_package}		com.itsoninc.android.itsonclient
${this_email_address}		None
 
*** Keywords ***
Open Application On Device
    [Documentation]         Retrieve all necessary information about the device and launch an appium session.
    ...                     Note: Make sure your device is stated within deviceManifest.
    Log To Console          Starting application
    listOfDevices
    ${port}=                get_port
    ${platform_name}=       get_platform
    ${platform_version}=    get_version
    ${app}=                 get_app
    ${device_type_tmp}      get_device_info
    Set Suite Variable      ${device_type}      ${device_type_tmp}
	${current_device_email}	get_emailid
    ${this_email_address}=	Set Variable If		'${this_email_address}' == 'None'           ${current_device_email}        ${this_email_address}	
    ${android_app_package}=	Set Variable If				'${app}' == 'None'      	  ${android_app_package}	     
    ...						'${app}' == '${EMPTY}'		${android_app_package}	      ${app}    
    Run Keyword If          '${platform_name}' == 'Android'     Run Keyword And Ignore Error     open_application    ${remote_url}   ${platform_name}    ${platform_version}     ${device_name}      ${app}  ${automation_name}  ${android_app_package}      ${android_app_activity}
    Run Keyword If          '${platform_name}' == 'iOS'         Run Keyword And Ignore Error     open_application    ${remote_url}   ${platform_name}    ${platform_version}     ${device_name}      ${app}
	Log To Console			${android_app_package}
    Sleep                   ${timeout}               
    : FOR    ${i}      IN RANGE    2
    \		Log To Console          Detecting any un-expected windows/errors popup during Open Application. Retrying... ${i+1}/2
	\		${status}               ${verify_text}=     			Run Keyword And Ignore Error    Wait Until Page Contains    		$




————
And here is the bach_profile:


# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
# PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
PATH="/Library/Python/2.7:${PATH}"
export PATHJAVA_HOME=/usr/bin/java
export JAVA_HOME
PYTHON_PATH=/usr/bin
export PYTHON_PATH
export DYLD_LIBRARY_PATH=/Users/vunguyen/imobiledevice-macosx/:$DYLD_LIBRARY_PA$
PATH=${PATH}:/Users/vunguyen/imobiledevice-macosx/


# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
#PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
PATH="/Library/Python/2.7:${PATH}"
export PATH

ROOT_HOME=$(pwd)

export ANDROID_HOME=$ROOT_HOME/automation/android-sdk-linux
#export PYTHON_PATH="/Library/Python/2.7"
#export PYTHON_PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin"
export JAVA_HOME="Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk"
export PATH=${PATH}:$JAVA_HOME:$PYTHON_PATH
export PATH=$PATH:$HOME/.npm-packages/bin

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

All the patch are correct ?

Thanks so much,
VuNguyen

**Comment by jollychang** [comment]
is there some specify character ?
as traceback mentioned, it is may be some decode issue.
```
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
obj, end = self.scan_once(s, idx)
```

**Comment by rockyav** [comment]
Nope, there is no specify character in the keyword file.
But I’m not sure in lib 

Do you check my bah_profile file ?Is it correct ?

Regards,
VuNguyen

**Comment by jollychang** [comment]
your bash_profile doesn't  show some special

**Comment by rockyav** [comment]
All the environment are configured OK ?

**Comment by rockyav** [comment]
Sorry, I'm new QA automation tester here.
