### ISSUE TITLE
   element_should_be_disabled and  element_should_be_enabled missing loglevel

### ISSUE THREAD

**Issue by jinesh900** [jollychang/robotframework-appiumlibrary#49]
When element should be disabled or element should be enabled fails it does not log the error. Instead it states global name loglevel is not defined.

The reason is its missing loglevel. It appears as     def element_should_be_disabled(self, locator):

it should be def element_should_be_disabled(self, locator, loglevel='INFO')

Same for enabled keyword.

**Comment by jollychang** [comment]
Is it fix on https://github.com/jollychang/robotframework-appiumlibrary/pull/45/files ?
