### ISSUE TITLE
Cannot access element in webview

### ISSUE THREAD

**Issue by johanlajili** [jollychang/robotframework-appiumlibrary#54]
Hi. I'm pretty new with automated testing. I am trying to access divs inside a webview to click on element.
If I open the appium inspector, I can only see inside the webview the divs that contain text (they are identified as a **UIAStaticText** element). All others are ignored. Even if I try to access it regardless, using
     Tap    //div[@id='button']
it says the element does not exist. I precise I switch to WEBVIEW_1 before that.

**Comment by jollychang** [comment]
Could you provide more log(both appium server and robotframework-appiumlibrary)?
