### ISSUE TITLE
No Keyword existing for executing JavaScript and getting text of element in appium library

### ISSUE THREAD

**Issue by Sumeet90** [jollychang/robotframework-appiumlibrary#62]
I want to execute JavaScript for various action get text value, swipe, scroll. So is it possible to have keyword like 'Execute JavaScript'. 
Also there is no keyword existing for getting text value of element because I want fetch text value of element.

eg:
execute_script("mobile: swipe", {"startX": 0.9, "startY": 0.9, "endX": 0.9, "endY": 0.9, "endY": 3.0})

**Comment by jollychang** [comment]
you can use [Swipe](http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html#Swipe)

**Comment by Sumeet90** [comment]
But how to get text of an element ???

**Comment by jollychang** [comment]
try [this](http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html#Element%20Name%20Should%20Be)?

**Comment by Sumeet90** [comment]
Thank you so much for replying ...

I am using same library but there is no keyword for fetch text value like 'Get Text'.

**Comment by pandabat** [comment]
Indeed there isn't.

I tried the suggested keyword and no joy. Basically, if we have something like this in an Android app: 

<div id="home-submenus" style="-webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"> 
     <div id="home-submenu-home" data-submenu-view="HomeSubMenu" class="show"> 
<div id="home-time" style="-webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"> 
     <h1>17:54</h1> 
     <h3>Tuesday 1 March 2016</h3> 
</div>

I want to be able to get the text "Tuesday 1 March 2016" (or whatever value it has at the time).

Using "Element Name Should Be" and "Element Value Should Be", I get fail result "Element 'css=#home-time' name should be 'Tuesday 1 March 2016' but it is 'None'."

Using " Element Attribute Should Match, css=#home-time, text, Tues* ", I get TypeError: expected string or buffer.

Can't seem to get actual text values like with the Get Text keyword in, say, Selenium2Library

**Comment by pandabat** [comment]
Raising again in  Getting Elements Text Attribute #98

**Comment by pandabat** [comment]
You can edit your _elements.py and add something like:

def get_element_text(self, locator):
    element = self._element_find(locator, True, True)
    element_text = element.text
    self._info("Element '%s' text: %s " % (locator, element_text))
    return element_text

Should work until they add something official

**Comment by CapDam** [comment]
how does one go because the changes I make are not reflected in robot-framework

I added the keyword in _elements.py but robot framework does not recognize
