### ISSUE TITLE
keywords are too less for testing hybrid APP

### ISSUE THREAD

**Issue by valaxy** [jollychang/robotframework-appiumlibrary#63]
Hi all, I have a idea.
[AppiumLibrary](http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html) has 51 keywords
[Selenium2Library](http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html) has 163 keywords
As wee all know, appium is a framework extended from selenium, so AppiumLibrary should have more selenium keywords

Developing all of the keywords is a very tedious work, besides, Selenium2Library has already implemented them. Why not consider combining the 2 library when we in test work?

If this is really valueable, I will provide a new keyword that making the 2 librarys work together and fork/pull a request.

**Comment by jollychang** [comment]
you'd better open a issue in Selenium2Library
