### ISSUE TITLE
How to request addition of new keywords.

### ISSUE THREAD

**Issue by AutomationPlus** [jollychang/robotframework-appiumlibrary#64]
Hi, I've been using appium library for about a year, and I made some modifications to _element.py to add some keywords from selenium2. Kaywords that doesn't come by default.
How is the procedure to add this changes to the master. 
I would like to share my modifications whit the comunity.
Thanks!

**Comment by jollychang** [comment]
[Fork the project, make a change, and send a pull request!](https://github.com/jollychang/robotframework-appiumlibrary#contributing)

**Comment by CapDam** [comment]
Can you explain the process to change the file element.py and that robot framework recognizes the new keyword ?
