### ISSUE TITLE
Switch Application keyword is not working properly with same UDID or device

### ISSUE THREAD

**Issue by Sumeet90** [jollychang/robotframework-appiumlibrary#66]
I have executed below code on same device with UDID as 039d220c43819f72. In code I have opened two applications on different port and both applications are opened successfully. But when i switch application from 2->1 or 1>2 using 'Switch Application' keyword then application is not switched. Can anyone please suggest any way to resolve this issue.

${appium2}	Open Application	http://127.0.0.1:4755/wd/hub	platformName=Android	platformVersion=4.4.2	deviceName=Nexus5			automationName=appium	udid=039d220c43819f72	appPackage=com.whatsapp	appActivity=com.whatsapp.Main
	${appium1}	Open Application	http://127.0.0.1:4723/wd/hub	platformName=Android	platformVersion=5.1.1	deviceName=Nexus5			automationName=appium	udid=039d220c43819f72	appPackage=com.android.calculator2	appActivity=com.android.calculator2.Calculator
	Capture Page Screenshot
	Switch Application	${appium2}
	Click Element	id=com.whatsapp:id/menuitem_search
	Switch Application	${appium1}

**Comment by jollychang** [comment]
`Switch Application` is Switches the active application by index or alias.

http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html#Switch%20Application

**Comment by Sumeet90** [comment]
Thank you so much for your reply.

I have used Switch Application keyword both ways as index and alias. But application is not able to switch and i don't get any success till now. 

I don't know what is my mistake so can you please tell me what i have done something wrong in the above code.

**Comment by jollychang** [comment]
as your code , you don't use index or alias?

**Comment by Sumeet90** [comment]
Switch Application ${appium2}

I have stored index in ${appium2} variable which was actually returned by Open Application keyword

**Comment by jollychang** [comment]
you can check more detail logs,both appium server and android devices

**Comment by Sumeet90** [comment]
I have noticed one thing that keyword is working properly when i used it with two different device. If i open two application with different port on same device then issue occurred.

From APPIUM Logs as per below and i fond that after opening second application appium session is closed.

.......info: [debug] UiAutomator exited
.......info: [debug] executing cmd: /home/sumeet/android-sdk-linux/platform-tools/adb -s 039d220c43819f72 shell "echo 'ping'"
.......info: [debug] Attempting to uninstall app
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session

**Comment by jollychang** [comment]
I think this is a appium's issue, you can open a issue in appium project

**Comment by otmgue** [comment]
I have the same problem and the same logs

**Comment by SamyQAZ** [comment]
Hi, I am trying to switch from MY.app to gmail.app using Appium and robot framework.

I am unable to understand alias creation from the documentation. 
Below is code for alias creation,
```
${appium1}       Open Application    ${APPIUM_SERVER}    platformName=Android    platformVersion=${PLATFORM_VERSION}    autoGrantPermissions=True
    ...                 deviceName=${DEVICE_NAME}    app=    appPackage=${APP_PACKAGE}  appActivity=${APP_ACTIVITY}
    ...                 unicodeKeyboard=True    resetKeyboard=True  session-override=True   clearSystemFiles=True    noReset=False

${appium2}      http://localhost:4730/wd/hub    platformName=${PLATFORM_NAME}    platformVersion=${PLATFORM_VERSION}    autoGrantPermissions=True
    ...                 deviceName=${DEVICE_NAME}    app=${gamilApp}    appPackage=${gmailApp_Package}  appActivity=${gmailApp_Activity}
    ...                 unicodeKeyboard=True    noReset=True
    Log To Console  \nLaunched app, build used for testing is located at '${gamilApp}'
```
Tried using keyword open app and switch app. Seems it doesn't work. 

Did anybody tried and achieved success in switching application.
