### ISSUE TITLE
Open android Firefox browser using Open Application

### ISSUE THREAD

**Issue by AutomationPlus** [jollychang/robotframework-appiumlibrary#67]
Hi, I am trayng to navigate to an url using the browser (i.e. firefox).
I am using keyword "go to url" after "open application"  but I am getting this error:

WebDriverException: Message: Not yet implemented. Please help us: http://appium.io/get-involved.html

I am opening installed firefox using this capabilities:

platformName: Android
platformVersion: 4.4
browserName: android
androidPackage: org.mozilla.firefox
appActivity: org.mozilla.firefox.App
automationName: Appium
language: PT
locale: pt_BR
appiumVersion: 1.4.7

I'm sure the error I mention is thrown from "go to url"

I'll apresiate any hep, Thanks!

**Comment by jollychang** [comment]
you can open a issue to appium project
