### ISSUE TITLE
Go To Url keyword

### ISSUE THREAD

**Issue by AutomationPlus** [jollychang/robotframework-appiumlibrary#75]
Hi, I need help with Go To Url keyword.
I'm using it as documentation says: first, I open application (firefox for example), this step works fine.
But when I call Go To Url | www.google.com I get this error:

WebDriverException: Message: Not yet implemented.

Is there any other way to open an url in the browser on a real device?

Thanks!

**Comment by jollychang** [comment]
You can open a issue to appium, https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md

**Comment by jollychang** [comment]
```
In [60]: desired_caps
Out[60]:
{'browser': 'Chrome',
 'browsers': 'Chrome',
 'deviceName': '0123456789ABCDEF',
 'platformName': 'Android',
 'platformVersion': '4.2'}
In [61]: from appium import webdriver
In [62]: driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
