### ISSUE TITLE
Automate push notifications

### ISSUE THREAD

**Issue by AutomationPlus** [jollychang/robotframework-appiumlibrary#77]
Hi, Is there any way to manage push notificatios from the notifications area on the device?

I need to open a push notification and che some data inside.

Thanks!

**Comment by serhatbolsu** [comment]
@AutomationPlus please refer to appium explanation:
https://discuss.appium.io/t/test-push-notifications/4559

In regard of Android keyword can be added to receive if they python API allows it. This function may be added in future PR however please do not hesitate to fork this library and open a pull request for this function.

**Comment by AutomationPlus** [comment]
Thanks!

**Comment by AutomationPlus** [comment]
Thanks! I will try to implement it on python, using java code as base.
