### ISSUE TITLE
Demo cannot run successfully on real device

### ISSUE THREAD

**Issue by softwarezhu** [jollychang/robotframework-appiumlibrary#84]
Hi, I found that the demo cannot run successfully on real device, but it can run successfully on simulator. 
The id locator `id=com.example.android.contactmanager:id/contactNameEditText` always fails like `Element locator 'id=com.example.android.contactmanager:id/contactNameEditText' did not match any elements.`
Can you help me solve this? Thanks.

**Comment by serhatbolsu** [comment]
I have not checked for demo test for some time. However library works adequately, please test with your own test case and application. Open a new ticket if you come across a problem
