### ISSUE TITLE
Cannot use keyword scroll

### ISSUE THREAD

**Issue by panjizeith** [jollychang/robotframework-appiumlibrary#85]
I have a problem with Scroll To Keywords, it cannot find the element.

This is the log from appium :
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[DESCRIPTION=continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[DESCRIPTION=continue_reading_button, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding continue_reading_button using ID with the contextId:  multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=com.woi.liputan6.android:id/continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=com.woi.liputan6.android:id/continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.woi.liputan6.android:id/continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=android:id/continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=android:id/continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=android:id/continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[DESCRIPTION=continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[DESCRIPTION=continue_reading_button]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[DESCRIPTION=continue_reading_button, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[]}

I use this test case 
Test Open App
    OpenApp
    Wait Until Page Contains            Top Stories
    Click Element                       id=article_title
    Wait Until Page Contains Element    id=article_image
    Scroll To                           id=comment_label
    Close Application

Can you give the demo how to use scroll and scroll To keyword ?

**Comment by panjizeith** [comment]
It seems scrolling using id is flaky, right now we using xpath for 'scroll to' keyword.
Also if somebody perhaps having similiar problem like us, don't forget to use 'timeout=' argument when using keyword like Wait Until Page Contains Element, especially if you having slow internet connection, it will help prevent the flaky test

**Comment by smaspe** [comment]
I am trying to scroll using something like 

    Scroll To        xpath=//android.widget.TextView[@text='Some text']

But the scroll fails if the object is off screen. Which is basically the whole point of scrolling. How do I get around this?

**Comment by aba-avargas** [comment]
I have this error now with Android, anybody could use scroll in Android?

Scroll is working in Ios.
