### ISSUE TITLE
KW: "Capture Page Screenshot" captures two files, not one.

### ISSUE THREAD

**Issue by CMTaylor** [jollychang/robotframework-appiumlibrary#89]
According to the documentation the KW "Capture Page Screenshot":
"...filename argument specifies the name of the file to write the screenshot into. If no filename is given, the screenshot is saved into file appium-screenshot-<counter>.png...".

When I do:
    | Capture Page Screenshot | Calculator_Keypad.png |
I get two identical screenshot files in the RF OutputDir:
   - Calculator_Keypad.png
   - appium-screenshot-1.png

I've looked at the code for capture_page_screenshot in the _screenshot.py file but cannot figure out why it would be capturing two files instead of just one.

**Comment by CMTaylor** [comment]
Further testing shows that this issue only happens on the first screen captured. Subsequent screens are captured ONLY to the given file name and not to the generated appium-screenshot... name.

**Comment by jollychang** [comment]
Try
| Capture Page Screenshot | "Calculator_Keypad.png" |

?
