### ISSUE TITLE
Locators matching multiple elements get first match, not first ENABLED match

### ISSUE THREAD

**Issue by CMTaylor** [jollychang/robotframework-appiumlibrary#94]
All the keywords that use the internal _element_find() method either tell it to return only the first match by setting the 2nd argument True, or do their own selection of the first returned element. In my application this is resulting in a Tap being attempted on a disabled button (id=dbtnOK), since it was created first but has since been disabled when overlaid with another dialog with an identically named (id=dbtnOK) button.

Unless there's a very good reason for returning disabled elements, or unless you can show me how to create a locator that only matches enabled elements, I propose to rewrite the internal _element_find() method to return the first ENABLED element, not simply the first element.

**Comment by serhatbolsu** [comment]
@CMTaylor did you try to use xpath and sending multiple key=value pairs ?
