### ISSUE TITLE
capture_page_screenshot ignores device orientation

### ISSUE THREAD

**Issue by CMTaylor** [jollychang/robotframework-appiumlibrary#95]
My application only works in Landscape orientation on iPad. I force this in my Appium server by passing it the `--orientation "Landscape"` command line argument. Unfortunately the capture_page_screenshot keyword method in robotframework-appiumlibrary ignores this orientation and captures the screenshot in portrait orientation and logs it this "twisted" way in the RF log.

**Comment by serhatbolsu** [comment]
I have not tested this in iPad, however if you have a fix do not hesitate to send a PR.

**Comment by serhatbolsu** [comment]
It seems this questions regards Appium more then this library. Please open another issue if you think there is still a problem
