### ISSUE TITLE
Getting Elements Text Attribute

### ISSUE THREAD

**Issue by pandabat** [jollychang/robotframework-appiumlibrary#98]
Follow on from #47 which was closed in error. Also relates to issue #62 which was closed referencing a keyword that does not seem to do the job.

Issue #47 closed with reason "I found it has been implemented and the keyword is Get Text" but no such keyword exists within robotframework-appium library

Basically, if we have something like this in an Android app: 
```
<div id="home-submenus" style="-webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"> 
     <div id="home-submenu-home" data-submenu-view="HomeSubMenu" class="show"> 
<div id="home-time" style="-webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"> 
     <h1>17:54</h1> 
     <h3>Tuesday 1 March 2016</h3> 
</div>
```
which would display as:

<div id="home-submenus" style="-webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"> 
     <div id="home-submenu-home" data-submenu-view="HomeSubMenu" class="show"> 
<div id="home-time" style="-webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"> 
     <h1>17:54</h1> 
     <h3>Tuesday 1 March 2016</h3> 
</div>

I want to be able to get the text "Tuesday 1 March 2016" (or whatever value it has at the time).

Using "Element Name Should Be" and "Element Value Should Be", I get fail result "Element 'css=#home-time' name should be 'Tuesday 1 March 2016' but it is 'None'."

Using " Element Attribute Should Match, css=#home-time, text, Tues* ", I get TypeError: expected string or buffer.

Can't seem to get actual text values like with the Get Text keyword in, say, Selenium2Library

**Comment by pandabat** [comment]
Something like this should do the trick:

    def get_element_text(self, locator):
        element = self._element_find(locator, True, True)
        element_text = element.text
        self._info("Element '%s' text: %s " % (locator, element_text))
        return element_text

**Comment by jollychang** [comment]
Can you use `Get Element Attribute `?

**Comment by pandabat** [comment]
No I could not get Get Element Attribute to work for this scenario

**Comment by goffioul** [comment]
This issue has been closed with a very cryptic answer. @jollychang would you mind providing a full example of how to retrieve the text of a DOM element within a webview. It seems that you tell everybody to use "Get Element Attribute", but so far nobody has succeeded.

**Comment by serhatbolsu** [comment]
@goffioul  there is a new method called `Get Text` please upgrade to beta release if you would like to use it this time

**Comment by goffioul** [comment]
@serhatbolsu This is really good news, thanks.

**Comment by hdave1985** [comment]
It worked for me with Get Text for me to fetch label text instead of Get Element Attribute.
